Name:           ros-indigo-ndt-registration
Version:        1.0.30
Release:        0%{?dist}
Summary:        ROS ndt_registration package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/ndt_registration
Source0:        %{name}-%{version}.tar.gz

Requires:       pcl-devel
Requires:       ros-indigo-ndt-map
Requires:       ros-indigo-pcl-ros
Requires:       ros-indigo-tf
Requires:       ros-indigo-tf-conversions
BuildRequires:  pcl-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-ndt-map
BuildRequires:  ros-indigo-pcl-ros
BuildRequires:  ros-indigo-tf
BuildRequires:  ros-indigo-tf-conversions

%description
Contains a new implementation of 3D NDT registration. Used to find the relative
positions of two point clouds.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Oct 09 2015 Todor Stoyanov <todor.stoyanov@oru.se> - 1.0.30-0
- Autogenerated by Bloom

* Thu Oct 08 2015 Todor Stoyanov <todor.stoyanov@oru.se> - 1.0.29-0
- Autogenerated by Bloom

