Name:           ros-indigo-ndt-fuser
Version:        1.0.30
Release:        0%{?dist}
Summary:        ROS ndt_fuser package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/ndt_fuser
Source0:        %{name}-%{version}.tar.gz

Requires:       mesa-libGL-devel
Requires:       mesa-libGLU-devel
Requires:       pcl-devel
Requires:       ros-indigo-laser-geometry
Requires:       ros-indigo-message-runtime
Requires:       ros-indigo-ndt-map
Requires:       ros-indigo-ndt-registration
Requires:       ros-indigo-ndt-visualisation
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-std-srvs
Requires:       ros-indigo-visualization-msgs
BuildRequires:  mesa-libGL-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  pcl-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cmake-modules
BuildRequires:  ros-indigo-laser-geometry
BuildRequires:  ros-indigo-ndt-map
BuildRequires:  ros-indigo-ndt-registration
BuildRequires:  ros-indigo-ndt-visualisation
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-std-srvs
BuildRequires:  ros-indigo-visualization-msgs

%description
ndt_fuser

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Oct 09 2015 Jari Saarinen <jari.p.saarinen@gmail.com> - 1.0.30-0
- Autogenerated by Bloom

* Thu Oct 08 2015 Jari Saarinen <jari.p.saarinen@gmail.com> - 1.0.29-0
- Autogenerated by Bloom

