Name:           ros-hydro-ndt-visualisation
Version:        1.0.28
Release:        0%{?dist}
Summary:        ROS ndt_visualisation package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/ndt_visualization
Source0:        %{name}-%{version}.tar.gz

Requires:       freeglut-devel
Requires:       mesa-libGL-devel
Requires:       mesa-libGLU-devel
Requires:       pcl-devel
Requires:       ros-hydro-message-runtime
Requires:       ros-hydro-ndt-map
Requires:       ros-hydro-pcl-ros
BuildRequires:  freeglut-devel
BuildRequires:  libXi-devel
BuildRequires:  libXmu-devel
BuildRequires:  mesa-libGL-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  pcl-devel
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-ndt-map
BuildRequires:  ros-hydro-pcl-ros

%description
Contains classes for creating an ndt visualization window. Initial
implementation on top of mrpt.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Fri Dec 05 2014 Jari Saarinen <jari.p.saarinen@gmail.com> - 1.0.28-0
- Autogenerated by Bloom

* Fri Dec 05 2014 Jari Saarinen <jari.p.saarinen@gmail.com> - 1.0.27-0
- Autogenerated by Bloom

* Wed Dec 03 2014 Jari Saarinen <jari.p.saarinen@gmail.com> - 1.0.26-0
- Autogenerated by Bloom

* Mon Dec 01 2014 Jari Saarinen <jari.p.saarinen@gmail.com> - 1.0.25-0
- Autogenerated by Bloom

* Tue Nov 25 2014 Jari Saarinen <jari.p.saarinen@gmail.com> - 1.0.23-0
- Autogenerated by Bloom

* Tue Nov 25 2014 Jari Saarinen <jari.p.saarinen@gmail.com> - 1.0.24-0
- Autogenerated by Bloom

* Fri Nov 21 2014 Jari Saarinen <jari.p.saarinen@gmail.com> - 1.0.22-0
- Autogenerated by Bloom

